### ISSUE TITLE
Support for multi-channel?

### ISSUE THREAD

**Issue by Livius90** [baby123456/MCDMA_1proxy_1chan_driver#1]
Hi!
Is it support to use 3 or more DMA channel in the driver? I have a MCDMA which has 3 TX channel in the PL, so i want to send datas to them in the same time in 3 parallel thread in Linux OS.

Is it possible with your dirver? For example in device-tree can it work?

```C
dma_proxy_h2c {
    compatible ="xlnx,dma_proxy";
    dmas = <&axi_mcdma_0 0 &axi_mcdma_0 1 &axi_mcdma_0 2>;
    dma-names = "h2c0", "h2c1", "h2c2";
}
```

**Comment by baby123456** [comment]
yes, need a little modify

**Comment by baby123456** [comment]
> Hi!
> Is it support to use 3 or more DMA channel in the driver? I have a MCDMA which has 3 TX channel in the PL, so i want to send datas to them in the same time in 3 parallel thread in Linux OS.
> 
> Is it possible with your dirver? For example in device-tree can it work?
> 
> ```c
> dma_proxy_h2c {
>     compatible ="xlnx,dma_proxy";
>     dmas = <&axi_mcdma_0 0 &axi_mcdma_0 1 &axi_mcdma_0 2>;
>     dma-names = "h2c0", "h2c1", "h2c2";
> }
> ```

yes, the cdev_exit and dma_proxy_probe function need some change .However, this is used with specific harware.

**Comment by Livius90** [comment]
So as i see it is not supported yet. :(
